spring.application.name=restfullApiAssignment

spring.datasource.url=jdbc:postgresql://localhost:8080/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=kigali123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
